### ISSUE TITLE
How to get viewer count for a stream/game

### ISSUE THREAD

**Issue by alexjudeking** [Freguglia/rTwitchAPI#2]
More of a question than an issue, but how do I retrieve the viewer count for a certain game or stream? Doesn't appear that the viewer_count variable exists.

Cheers

**Comment by Freguglia** [comment]
Hello, sorry for the (very) late response. I didn't receive a notification for some reason.

You can use the function `get_streams()$data` to retrieve the information including viewer count.  
You can also use the argument `game_id` to query streams of specific games.

As an example: `get_streams(game_id = 488552)$data[ ,c("user_name", "viewer_count")]` retrieves data of top streams for `game_id 488552` and selects only the `user_name` and `viewer_count` columns of the returned dataframe object.
